### ISSUE TITLE
Using embed strategy extendBackGround fails when using image with alpha layer

### ISSUE THREAD

**Issue by norbertvannobelen** [davidbyttow/govips#159]
Used versions and systems:

Govips: 2.3.1 & 2.4.0
libvips 8.10.5
On linux, alpine edge

I am trying to create the following:
A canvas of a fixed size with on there an image fitted to the canvas. The canvas has to have a transparent background (alpha layer/bandjoin_const of 255 is required).

After several tests it turns out that vips.ExtendBackground fails with an alpha layer present (and only with alpha layer present: ExtendBackground works happily if there is no alpha layer).

```go
func TestImage_Embed_ExtendBackgroundWithAlpha(t *testing.T) {
	goldenTest(t, "with_alpha.png", func(img *vips.ImageRef) error {
		return img.Embed(10, 10, 20, 20, vips.ExtendBackground)
	}, nil, nil)
}
```

Error returned:

```log
2021/01/09 16:31:25 [govips.info] vips 8.10.5 started with concurrency=1 cache_max_files=0 cache_max_mem=52428800 cache_max=100
2021/01/09 16:31:25 [govips.info] registered image type loader type=jpeg
2021/01/09 16:31:25 [govips.info] registered image type loader type=png
2021/01/09 16:31:25 [govips.info] registered image type loader type=webp
2021/01/09 16:31:25 [govips.info] registered image type loader type=gif
2021/01/09 16:31:25 [govips.info] registered image type loader type=svg
2021/01/09 16:31:25 [govips.info] registered image type loader type=tiff
2021/01/09 16:31:25 [govips.info] registered image type loader type=heif
--- FAIL: TestImage_Embed (0.02s)
    main_test.go:28: 
                Error Trace:    main_test.go:28
                                                        main_test.go:16
                Error:          Received unexpected error:
                                linear: vector must have 1 or 4 elements
                            
                                Stack:
                                goroutine 19 [running]:
                                runtime/debug.Stack(0x7f134a4fe5a0, 0xc0000a03c0, 0x29)
                                        /usr/lib/go/src/runtime/debug/stack.go:24 +0x9f
                                github.com/davidbyttow/govips/v2/vips.handleVipsError(0x0, 0xc0ffffffff)
                                        /go/pkg/mod/github.com/davidbyttow/govips/v2@v2.3.1/vips/error.go:39 +0x58
                                github.com/davidbyttow/govips/v2/vips.handleImageError(0x0, 0xc0000a60e8, 0xa)
                                        /go/pkg/mod/github.com/davidbyttow/govips/v2@v2.3.1/vips/error.go:24 +0x2c
                                github.com/davidbyttow/govips/v2/vips.vipsEmbed(0x7f13200ab1a0, 0xa, 0xa, 0x14, 0x14, 0x5, 0x675420, 0x69af00, 0x6ce060)
                                        /go/pkg/mod/github.com/davidbyttow/govips/v2@v2.3.1/vips/conversion.go:140 +0xaa
                                github.com/davidbyttow/govips/v2/vips.(*ImageRef).Embed(0xc000122980, 0xa, 0xa, 0x14, 0x14, 0x5, 0x0, 0xc000099201)
                                        /go/pkg/mod/github.com/davidbyttow/govips/v2@v2.3.1/vips/image.go:781 +0x68
                                temp/imageProcessing.TestImage_Embed.func1(0xc000122980, 0xc000082900, 0x0)
                                        /go/src/build/main_test.go:17 +0x58
                                temp/imageProcessing.goldenTest(0xc000082900, 0x685bc9, 0xe, 0x69b050, 0x0, 0x0, 0x5ff9da5d, 0x246ce890, 0x188002ee35e04)
                                        /go/src/build/main_test.go:27 +0xae
                                temp/imageProcessing.TestImage_Embed(0xc000082900)
                                        /go/src/build/main_test.go:16 +0x54
                                testing.tRunner(0xc000082900, 0x69b058)
                                        /usr/lib/go/src/testing/testing.go:1123 +0xef
                                created by testing.(*T).Run
                                        /usr/lib/go/src/testing/testing.go:1168 +0x2b3
                Test:           TestImage_Embed
FAIL
exit status 1
FAIL    temp/imageProcessing    0.053s
```

Diving into the error:

```log
linear: vector must have 1 or 4 elements
```

which comes from the code in libvips:

```c
int
vips_check_vector( const char *domain, int n, VipsImage *im )
{
	if( n != 1 && im->Bands != 1 && n != im->Bands ) {
		vips_error( domain, 
			_( "vector must have 1 or %d elements" ), im->Bands );
		return( -1 );
	}

	return( 0 );
}
```

The number of bands seems to throw this error.

Checking for the bands in the image:

```go
func main() {
	vips.Startup(nil)
	vips.LoggingSettings(nil, vips.LogLevelDebug)
	defer vips.Shutdown()
	imageref, err := vips.NewImageFromFile("with_alpha.png")
	log.Printf("has alpha: %t, and bands %d. Errors: %v", imageref.HasAlpha(), imageref.Bands(), err)
}
```

Output:

```log
2021/01/09 16:40:47 has alpha: true, and bands 4. Errors: <nil>
```

Matching this output in govips, bands 4, with the requirement as stated in the libvips err: Must have 1 or 4 bands, it matches with the requirement but still fails to execute.

**Verification if the file would actually work with libvips**

Running with vips command line:

```sh
vips embed with_alpha.png out.png 1 1 2000 2000 --extend background
```

Results in the expected image (however hard to see the result). Easier to visually verify the result is with this command line example:

```sh
vips bandjoin_const png-24bit.png png-24bit-alpha.png 255
vips embed png-24bit-alpha.png out24.png 1 1 2000 2000 --extend background
```

Tracking the embed code I also looked at `conversion.c`

```c
int embed_image(VipsImage *in, VipsImage **out, int left, int top, int width, int height, int extend, double r, double g, double b) {
	if (extend == VIPS_EXTEND_BACKGROUND) {
		double background[3] = {r, g, b};
		VipsArrayDouble *vipsBackground = vips_array_double_new(background, 3);

		int code = vips_embed(in, out, left, top, width, height, "extend", extend, "background", vipsBackground, NULL);

		vips_area_unref(VIPS_AREA(vipsBackground));
		return code;
	}
	return vips_embed(in, out, left, top, width, height, "extend", extend, NULL);
}
```

Running a command line simulation of the equivalent vips embed resulting line with a valid value for `vipsBackground`:

```sh
vips embed with_alpha.png out.png 1 1 2000 2000 --extend background --background 100
```

Results in the expected image.

(I do not have a C compiler installed outside of the containers limiting me in supplying debug information on  what the actual content of the calls is. I suspect that the vipsBackground contains an invalid value for images with alpha, which gets parsed in the end by the vips_embed function, resulting in the observed difference between command line behaviour and c call behaviour).

**Comment by davidbyttow** [comment]
Thank you for the great summary and breakdown @norbertvannobelen, I will follow-up on this over the next few days.

**Comment by davidbyttow** [comment]
This should be fixed here: https://github.com/davidbyttow/govips/pull/165
