### ISSUE TITLE
VipsOperation: class "gifsave_buffer" not found

### ISSUE THREAD

**Issue by IAkumaI** [davidbyttow/govips#276]
Hi. I tried use library on Alpine docker image and saving to GIF does not work. Can you help me - what's wrong?

Dockerfile:
```
FROM golang:1.18.0-alpine

RUN apk update && \
    apk add bash git gcc musl-dev openssh libc-dev \
      vips vips-dev \
      libjpeg librsvg libpng giflib imagemagick

# install glibc https://github.com/sgerrand/alpine-pkg-glibc
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
    && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.34-r0/glibc-2.34-r0.apk \
    && apk add glibc-2.34-r0.apk
```

Save to JPG, SVG, PNG works file. But when I try to save GIF errors shows: 
```
VipsOperation: class "gifsave_buffer" not found
Stack:
goroutine 2696 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/davidbyttow/govips/v2/vips.handleVipsError()
	/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.11.0/vips/error.go:38 +0x57
github.com/davidbyttow/govips/v2/vips.handleSaveBufferError(0xc00003ca00?)
	/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.11.0/vips/error.go:31 +0x25
github.com/davidbyttow/govips/v2/vips.vipsSaveToBuffer({0x7fec88eafb10, 0x0, 0x5, 0x0, 0x0, 0x4b, 0x0, 0x0, 0x1, 0x0, ...})
	/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.11.0/vips/foreign.go:440 +0xb7
github.com/davidbyttow/govips/v2/vips.vipsSaveGIFToBuffer(0x7fec88eafb10, {0x0, 0x4b, 0x0, 0x7, 0x8})
	/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.11.0/vips/foreign.go:435 +0x159
github.com/davidbyttow/govips/v2/vips.(*ImageRef).ExportGIF(0xc000840280, 0xc0000d5240?)
	/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.11.0/vips/image.go:918 +0xaf
github.com/davidbyttow/govips/v2/vips.(*ImageRef).ExportNative(0xc000143d10?)
	/go/pkg/mod/github.com/davidbyttow/govips/v2@v2.11.0/vips/image.go:833 +0x22f
```

**Comment by IAkumaI** [comment]
Same code works fine on my Macbook, but I can't make it works in alpine docker image.

**Comment by sbraty** [comment]
Which version of vips installed ? gifsave works from version 8.12

You can try to build vips from sources:
```
ENV VIPS_VERSION=8.12.2
ARG VIPS_URL=https://github.com/libvips/libvips/releases/download

ADD ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz \
  /tmp/

RUN cd /tmp 
  && tar xf vips-${VIPS_VERSION}.tar.gz \
  && cd vips-${VIPS_VERSION} \
  && ./configure --without-magick --without-pangoft2 --without-ppm \
       --without-analyze --without-radiance --without-OpenEXR \
       --with-jpeg-includes=/opt/mozjpeg/include \
       --with-jpeg-libraries=/opt/mozjpeg/lib64 \
  && make -j4 V=0 \
  && make install \
  && rm -rf /tmp/*
```

**Comment by IAkumaI** [comment]
Vips 8.12

So, I just change docker image from alpine to debian and all works fine.
Building from sources does not works on alpine cause of bug in docker 19v

**Comment by sbraty** [comment]
I can't check on docker 19v , but on 20v this dockerfile built fine 

```
FROM golang:1.18.0-alpine

RUN apk update && apk upgrade

RUN apk add build-base autoconf automake libtool bc \
	zlib-dev expat-dev jpeg-dev tiff-dev glib-dev libjpeg-turbo-dev libexif-dev \
	lcms2-dev fftw-dev giflib-dev libpng-dev libwebp-dev orc-dev libgsf-dev

ENV VIPS_VERSION=8.12.2
ARG VIPS_URL=https://github.com/libvips/libvips/releases/download

ADD ${VIPS_URL}/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz \
  /tmp/

RUN cd /tmp \
  && tar xf vips-${VIPS_VERSION}.tar.gz \
  && cd vips-${VIPS_VERSION} \
  && ./configure \
  && make -j4 V=0 \
  && make install \
  && rm -rf /tmp/*
```

**Comment by IAkumaI** [comment]
Will check this soon and back with result

**Comment by IAkumaI** [comment]
Still `VipsOperation: class "gifsave_buffer" not found` error.

Well. Even without gif alpine image ~600Mb. But debian-based only ~900Mb (+300) - not so much. So, I think I can just use debian-base images which works with all formats.
Thank you, after all

P.S. Your dockerfile fails on docker 19, but works in docker 20.
