### ISSUE TITLE
Bug: Can't export same image twice

### ISSUE THREAD

**Issue by ubombi** [davidbyttow/govips#297]
Probably the bug. When I try export ThumbnailFromBuffer twice.

```go
// Broken, fails with error
img, _ := vips.NewThumbnailFromBuffer(...)
img.ExportWebp(...)
img.ExportPng(...)


// Works well
img, _ := vips.NewImageFromBuffer(...)
img.Thumbnail()
img.ExportWebp(...)
img.ExportPng(...)
```

Export once (any format) works both ways.

```
vipspng: out of order read at line 2560

Stack:
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
github.com/davidbyttow/govips/v2/vips.handleVipsError()
	github.com/davidbyttow/govips/v2@v2.11.0/vips/error.go:38 +0x57
github.com/davidbyttow/govips/v2/vips.handleSaveBufferError(0xc00003ca00?)
	github.com/davidbyttow/govips/v2@v2.11.0/vips/error.go:31 +0x25
github.com/davidbyttow/govips/v2/vips.vipsSaveToBuffer({0x7f11dc135ca0, 0x0, 0x2, 0x0, 0x0, 0x64, 0x0, 0x0, 0x1, 0x0, ...})
	github.com/davidbyttow/govips/v2@v2.11.0/vips/foreign.go:440 +0xb7
github.com/davidbyttow/govips/v2/vips.vipsSaveWebPToBuffer(0x7f11dc135ca0, {0x0, 0x64, 0x1, 0x0, 0x6, {0x0, 0x0}})
	github.com/davidbyttow/govips/v2@v2.11.0/vips/foreign.go:370 +0x1f8
github.com/davidbyttow/govips/v2/vips.(*ImageRef).ExportWebp(0xc00008a690, 0x71?)
	github.com/davidbyttow/govips/v2@v2.11.0/vips/image.go:876 +0xc5
```

**Comment by tonimelisma** [comment]
Hey @ubombi I can't recreate this with latest on macOS 12.6 and latest homebrew vips. I added a unit test for you but it's passing:

```
func TestDoubleExport(t *testing.T) {
	Startup(nil)

	srcBytes, err := ioutil.ReadFile(resources + "copyright.jpeg")
	require.NoError(t, err)

	src := bytes.NewReader(srcBytes)
	img, err := NewImageFromReader(src)
	require.NoError(t, err)
	require.NotNil(t, img)

	_, _, err = img.ExportWebp(nil)
	assert.NoError(t, err)

	_, _, err = img.ExportPng(nil)
	assert.NoError(t, err)
}
```

Result:
```
tonimelisma@Tonis-MacBook-Pro govips % go test -v ./... -run TestDoubleExport
?       github.com/davidbyttow/govips/v2/examples/jpeg  [no test files]
testing: warning: no tests to run
PASS
ok      github.com/davidbyttow/govips/v2/examples/logging       (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/davidbyttow/govips/v2/examples/thumbnail     (cached) [no tests to run]
?       github.com/davidbyttow/govips/v2/examples/tiff  [no test files]
=== RUN   TestDoubleExport
2022/10/07 19:18:51 [VIPS.info] found /opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13
2022/10/07 19:18:51 [VIPS.info] using configure-time prefix
2022/10/07 19:18:51 [VIPS.info] VIPS_PREFIX = /opt/homebrew/Cellar/vips/8.13.1_1
2022/10/07 19:18:51 [VIPS.info] VIPS_LIBDIR = /opt/homebrew/Cellar/vips/8.13.1_1/lib
2022/10/07 19:18:51 [VIPS.info] prefix = /opt/homebrew/Cellar/vips/8.13.1_1
2022/10/07 19:18:51 [VIPS.info] libdir = /opt/homebrew/Cellar/vips/8.13.1_1/lib
2022/10/07 19:18:51 [VIPS.info] searching "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13"
2022/10/07 19:18:51 [VIPS.info] loading "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13/vips-jxl.so"
2022/10/07 19:18:51 [VIPS.info] loading "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13/vips-poppler.so"
2022/10/07 19:18:51 [VIPS.info] loading "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13/vips-heif.so"
2022/10/07 19:18:51 [VIPS.info] loading "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13/vips-openslide.so"
2022/10/07 19:18:51 [VIPS.info] loading "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13/vips-magick.so"
2022/10/07 19:18:51 [VIPS.info] searching "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-plugins-8.13"
2022/10/07 19:18:51 [govips.info] vips 8.13.1 started with concurrency=1 cache_max_files=0 cache_max_mem=52428800 cache_max=100
2022/10/07 19:18:51 [govips.info] registered image type loader type=jpeg
2022/10/07 19:18:51 [govips.info] registered image type loader type=magick
2022/10/07 19:18:51 [govips.info] registered image type loader type=pdf
2022/10/07 19:18:51 [govips.info] registered image type loader type=png
2022/10/07 19:18:51 [govips.info] registered image type loader type=tiff
2022/10/07 19:18:51 [govips.info] registered image type loader type=webp
2022/10/07 19:18:51 [govips.info] registered image type loader type=heif
2022/10/07 19:18:51 [govips.info] registered image type loader type=heif
2022/10/07 19:18:51 [govips.info] registered image type loader type=gif
2022/10/07 19:18:51 [govips.info] registered image type loader type=svg
2022/10/07 19:18:51 [govips.info] registered image type loader type=jp2k
--- PASS: TestDoubleExport (0.06s)
PASS
ok      github.com/davidbyttow/govips/v2/vips   0.254s
2022/10/07 19:17:19 [VIPS.info] found /opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13
2022/10/07 19:17:19 [VIPS.info] using configure-time prefix
2022/10/07 19:17:19 [VIPS.info] VIPS_PREFIX = /opt/homebrew/Cellar/vips/8.13.1_1
2022/10/07 19:17:19 [VIPS.info] VIPS_LIBDIR = /opt/homebrew/Cellar/vips/8.13.1_1/lib
2022/10/07 19:17:19 [VIPS.info] prefix = /opt/homebrew/Cellar/vips/8.13.1_1
2022/10/07 19:17:19 [VIPS.info] libdir = /opt/homebrew/Cellar/vips/8.13.1_1/lib
2022/10/07 19:17:19 [VIPS.info] searching "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13"
2022/10/07 19:17:19 [VIPS.info] loading "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13/vips-jxl.so"
2022/10/07 19:17:19 [VIPS.info] loading "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13/vips-poppler.so"
2022/10/07 19:17:19 [VIPS.info] loading "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13/vips-heif.so"
2022/10/07 19:17:19 [VIPS.info] loading "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13/vips-openslide.so"
2022/10/07 19:17:19 [VIPS.info] loading "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-modules-8.13/vips-magick.so"
2022/10/07 19:17:19 [VIPS.info] searching "/opt/homebrew/Cellar/vips/8.13.1_1/lib/vips-plugins-8.13"
2022/10/07 19:17:19 [govips.info] vips 8.13.1 started with concurrency=8 cache_max_files=0 cache_max_mem=0 cache_max=0
2022/10/07 19:17:19 [govips.info] registered image type loader type=magick
2022/10/07 19:17:19 [govips.info] registered image type loader type=pdf
2022/10/07 19:17:19 [govips.info] registered image type loader type=png
2022/10/07 19:17:19 [govips.info] registered image type loader type=tiff
2022/10/07 19:17:19 [govips.info] registered image type loader type=heif
2022/10/07 19:17:19 [govips.info] registered image type loader type=jp2k
2022/10/07 19:17:19 [govips.info] registered image type loader type=gif
2022/10/07 19:17:19 [govips.info] registered image type loader type=jpeg
2022/10/07 19:17:19 [govips.info] registered image type loader type=svg
2022/10/07 19:17:19 [govips.info] registered image type loader type=webp
2022/10/07 19:17:19 [govips.info] registered image type loader type=heif
testing: warning: no tests to run
PASS
ok      github.com/davidbyttow/govips/v2/vips/mem_tests (cached) [no tests to run]
tonimelisma@Tonis-MacBook-Pro govips % 
```

**Comment by tonimelisma** [comment]
Closing for now but let me know if you can recreate.
