### ISSUE TITLE
Build Failure under Go 1.8

### ISSUE THREAD

**Issue by andrewgleave** [davidbyttow/govips#4]
Platform: **Darwin 15.6.0**
Go Version: **1.8**
VIPS Version: **vips-8.4.5-Wed Jan  4 05:36:05 PST 2017** (homebrew)

Not building with the following errors:

    go get -u gopkg.in/davidbyttow/govips.v0
    # gopkg.in/davidbyttow/govips.v0
    ../gopkg.in/davidbyttow/govips.v0/options.go:72: cannot use src.(*Image).image (type *C.struct__VipsImage) as type C.gpointer in argument to func literal
    ../gopkg.in/davidbyttow/govips.v0/options.go:82: cannot use src.(*Blob).cBlob (type *C.struct__VipsBlob) as type C.gconstpointer in argument to func literal
    ../gopkg.in/davidbyttow/govips.v0/options.go:92: cannot use src.(*Interpolator).interp (type *C.struct__VipsInterpolate) as type C.gpointer in argument to func literal

**Comment by andrewgleave** [comment]
Fixed in https://github.com/davidbyttow/govips/pull/5

**Comment by superdump** [comment]
After applying this, I'm getting a segfault:

```
BenchmarkGovips-8
(govips:83992): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(govips:83992): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(govips:83992): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(govips:83992): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(govips:83992): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(govips:83992): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(govips:83992): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(govips:83992): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(govips:83992): GLib-CRITICAL **: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(govips:83992): GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x437b80e]

runtime stack:
runtime.throw(0x4189c36, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 160 [syscall, locked to thread]:
runtime.cgocall(0x412bd40, 0xc42003fcb8, 0xc42000e078)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc42003fc88 sp=0xc42003fc48
github.com/davidbyttow/govips._Cfunc_vips_cache_operation_buildp(0xc42000e078, 0xc400000000)
	github.com/davidbyttow/govips/_obj/_cgo_gotypes.go:707 +0x49 fp=0xc42003fcb8 sp=0xc42003fc88
github.com/davidbyttow/govips.vipsCallOperation.func2(0xc42000e078, 0x55a8390)
	/Users/robertsw/src/thumbnailer/vendor/src/github.com/davidbyttow/govips/bridge.go:129 +0xbd fp=0xc42003fd00 sp=0xc42003fcb8
github.com/davidbyttow/govips.vipsCallOperation(0x6a5abc0, 0xc42003fe28, 0x0, 0x0)
	/Users/robertsw/src/thumbnailer/vendor/src/github.com/davidbyttow/govips/bridge.go:129 +0xc2 fp=0xc42003fd68 sp=0xc42003fd00
github.com/davidbyttow/govips.vipsCall(0x41820d4, 0x6, 0xc42003fe28, 0x3fc999999999999a, 0xc42003fe28)
	/Users/robertsw/src/thumbnailer/vendor/src/github.com/davidbyttow/govips/bridge.go:108 +0x4d fp=0xc42003fd98 sp=0xc42003fd68
github.com/davidbyttow/govips.(*Image).ResizeEx(0xc42000e050, 0x3fc999999999999a, 0xc42003fe28, 0xc42000e058)
	/Users/robertsw/src/thumbnailer/vendor/src/github.com/davidbyttow/govips/operators.go:4236 +0x104 fp=0xc42003fdf0 sp=0xc42003fd98
thumbnailer.ThumbnailWithGovips(0xc4200fa000, 0x4e, 0x4182a56, 0x9, 0x280, 0x1e0, 0x0, 0x0)
	/Users/robertsw/src/thumbnailer/src/thumbnailer/benchmark.go:29 +0x1cc fp=0xc42003fe68 sp=0xc42003fdf0
thumbnailer.benchmark(0xc4200b6000, 0x418bd20)
	/Users/robertsw/src/thumbnailer/src/thumbnailer/benchmark_test.go:25 +0x1d2 fp=0xc42003ff18 sp=0xc42003fe68
thumbnailer.BenchmarkGovips(0xc4200b6000)
	/Users/robertsw/src/thumbnailer/src/thumbnailer/benchmark_test.go:19 +0x37 fp=0xc42003ff38 sp=0xc42003ff18
testing.(*B).runN(0xc4200b6000, 0x5)
	/usr/local/go/src/testing/benchmark.go:140 +0xb2 fp=0xc42003ff78 sp=0xc42003ff38
testing.(*B).launch(0xc4200b6000)
	/usr/local/go/src/testing/benchmark.go:281 +0x122 fp=0xc42003ffd8 sp=0xc42003ff78
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42003ffe0 sp=0xc42003ffd8
created by testing.(*B).doBench
	/usr/local/go/src/testing/benchmark.go:250 +0x70

goroutine 1 [chan receive]:
testing.(*B).doBench(0xc4200b6000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/testing/benchmark.go:251 +0x9a
testing.(*benchContext).processBench(0xc42000cc60, 0xc4200b6000)
	/usr/local/go/src/testing/benchmark.go:433 +0x1f7
testing.(*B).run(0xc4200b6000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/testing/benchmark.go:241 +0x6d
testing.(*B).Run(0xc4200b62c0, 0x4183c34, 0xf, 0x418bd08, 0x40b2e00)
	/usr/local/go/src/testing/benchmark.go:494 +0x24d
testing.runBenchmarks.func1(0xc4200b62c0)
	/usr/local/go/src/testing/benchmark.go:403 +0x67
testing.(*B).runN(0xc4200b62c0, 0x1)
	/usr/local/go/src/testing/benchmark.go:140 +0xb2
testing.runBenchmarks(0xc42000cc40, 0x42391a0, 0x3, 0x3, 0xc420050100)
	/usr/local/go/src/testing/benchmark.go:409 +0x48d
testing.(*M).Run(0xc420057f20, 0xc420057f20)
	/usr/local/go/src/testing/testing.go:828 +0x305
main.main()
	thumbnailer/_test/_testmain.go:46 +0xf7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
exit status 2
```

The code being executed was based on the resize example.

**Comment by superdump** [comment]
I'm not sure if it's related or not yet so I'll take this to a separate issue.

**Comment by superdump** [comment]
Works for me.

**Comment by davidbyttow** [comment]
Oops, apologies for missing this. Looks like this should be fixed now.
